Add `SET_DYNAMIC` API and tests
lf-lang/lingua-franca pull request #1097
Opened 2022-04-12 19:51 UTC by housengw

Related PR in reactor-c:

2022-04-13 01:15 UTC, edwardalee requested changes
Small error detected. Approve modulo changing function names to lower case.

2022-04-13 01:15 UTC, edwardalee commented on test/C/src/SetWithCustomDestructor.lf
> +        complex_t* val = (complex_t*) malloc(sizeof(int));
```suggestion
        complex_t* val = (complex_t*) malloc(sizeof(complex_t));
```

2022-04-13 01:15 UTC, edwardalee commented on test/C/src/SetWithCustomDestructor.lf
> +        val->size = 1000;
```suggestion
        val->size = 10;
```
(No need to make a test more expensive to run).

2022-04-13 05:10 UTC, housengw commented
Seems like a Windows specific problem is keeping `SetWithCustomConstructor` from passing on Windows

2022-04-26 05:19 UTC, Soroosh129 approved these changes
LGTM!

Before merging this, let's make sure everyone is aware of this change (maybe by announcing it on lf-interest) and that the website and/or the wiki are up-to-date.

2022-04-26 17:09 UTC, housengw commented
I can make an announcement. With regards to the website, I think we should merge the PR first. Otherwise we would have documentation that refer to code not in master

2022-04-26 18:44 UTC, edwardalee approved these changes
LGTM!  We can immediately update the website repo because that website is not live. But anyway, I think we should forge ahead with this...

2022-04-28 00:05 UTC, merged