Rust clap fix
lf-lang/lingua-franca pull request #1099
Opened 2022-04-14 10:34 UTC by jhaye

Previously inline arguments for the main reactor weren't handled in a way that was appropriate for clap, the CLI library used for Rust reactor programs. 
Basically, it couldn't handle arguments like this: `max_value: u64({= 1 << 60 =})`.

This PR upgrades to a stable version of clap and handles inline arguments correctly. This depends on #1098, so that should be merged first.

Ref: https://github.com/lf-lang/benchmarks-lingua-franca/issues/5

2022-04-19 12:30 UTC, cmnrd approved these changes
Cool! I converted this to draft and will merge this as soon as we have merged #1098.

2022-04-27 15:53 UTC, cmnrd requested changes
I think this needs to be rebased to the new master. It seems to still include some changes from #1098.

Also, could you add a test for this added functionality (or extend an existing test)?

2022-04-28 09:38 UTC, jhaye commented
I added a test, but not sure if it's automatically added to the bulk test run.

2022-04-28 10:59 UTC, cmnrd approved these changes
Yes, all the lf files in the test directories are run automagically. Thanks!

2022-04-28 10:59 UTC, merged