Layout improvements
lf-lang/lingua-franca pull request #1206
Opened 2022-05-31 11:45 UTC by a-sr

Bumps ELK version to 0.8.1 and activates new features.

2022-06-15 11:51 UTC, a-sr commented
All planned changes are implemented. PR is ready for review.

2022-06-15 18:15 UTC, lhstrh commented
Looks like we're still stuck with a Maven configuration that doesn't work...

2022-06-16 23:13 UTC, lhstrh requested changes
This looks excellent and ready to merge in, except for the missing Javadoc...

2022-06-16 23:13 UTC, lhstrh commented on org.lflang.diagram/src/org/lflang/diagram/synthesis/util/LayoutPostProcessing.java
> +    public static final SynthesisOption MODEL_ORDER =
Many methods in this file have no Javadoc. Could you please add those?

2022-06-16 23:13 UTC, lhstrh commented on org.lflang.diagram/src/org/lflang/diagram/synthesis/util/LayoutPostProcessing.java
> +}
Missing new line.

2022-06-16 23:13 UTC, lhstrh commented on org.lflang.diagram/src/org/lflang/diagram/synthesis/util/LayoutPostProcessing.java
> +}
Missing new line.

2022-06-21 07:22 UTC, lhstrh approved these changes
:rocket: :rocket: :rocket:

2022-06-22 08:27 UTC, merged