Implemented watchdog feature
lf-lang/lingua-franca pull request #1605
Opened 2023-02-26 23:35 UTC by Benichiwa

This implements the watchdog feature as mentioned in the discussion: "Watchdogs #1379". It may be causing issues with some single-threaded programs.

2023-02-28 04:25 UTC, Benichiwa commented
CI / unit-tests / run is failing as a result of a watchdog parsing error in "Watchdog.lf" during the roundTripTests(). Although this error gets thrown while running the tests on my local machine, this is not the case when running `lfc Watchdog.lf`.

2023-03-09 06:52 UTC, lhstrh commented on org.lflang/src/org/lflang/ASTUtils.java
> +    //FIXME: modif4watchdogs
According to the grammar, watchdogs don't have a value or type, so there appears to be nothing actionable here. Remove?

2023-03-09 06:53 UTC, lhstrh commented on org.lflang/src/org/lflang/LinguaFranca.xtext
> +        | (watchdogs+=Watchdog)
Can you move this up, right after the actions?

2023-03-09 06:53 UTC, lhstrh commented on org.lflang/src/org/lflang/LinguaFranca.xtext
> +        (watchdogs+=Watchdog)
Idem (watchdogs should come after actions)

2023-03-09 06:56 UTC, lhstrh requested changes
I'll continue my review once all the FIXMEs are gone...

2023-03-09 06:56 UTC, lhstrh commented on org.lflang/src/org/lflang/ast/IsEqual.java
> +    //FIXME: modif4watchdogs
```suggestion
```

2023-03-09 06:56 UTC, lhstrh commented on org.lflang/src/org/lflang/ast/IsEqual.java
> +        //FIXME: modif4watchdogs
```suggestion
```

2023-03-09 06:56 UTC, lhstrh commented on org.lflang/src/org/lflang/ast/ToLf.java
> +  //FIXME: modif4watchdogs
```suggestion
```

2023-05-21 23:38 UTC, closed without merging