Small fixes to make CI more robust
lf-lang/lingua-franca pull request #1895
Opened 2023-07-09 00:12 UTC by lhstrh

2023-07-10 08:58 UTC, cmnrd requested changes
Did you investigate the cause of the error in https://github.com/lf-lang/lingua-franca/pull/1894?

I don't think we should ignore codecov errors. If we do this, we don't notice if there are any problems in the reporting and whether we can trust the coverage report. Also see the discussion in https://github.com/lf-lang/lingua-franca/pull/1868.

I also think we should report on all platforms, not just Linux. We have some platform dependent code in our code base and will only get full coverage if we report on all platforms. https://github.com/lf-lang/lingua-franca/pull/1868 deliberately removed the platform check.

2023-07-10 18:26 UTC, lhstrh commented
Shall we then replace `if: ${{ github.repository == 'lf-lang/lingua-franca' && matrix.platform == 'ubuntu-latest' }}` with `if: ${{ github.repository == 'lf-lang/lingua-franca' }}` and merge this?

2023-07-10 22:49 UTC, lhstrh commented
Note this failure: https://github.com/lf-lang/lingua-franca/actions/runs/5512578023/jobs/10049603441?pr=1895

I think this will become a major annoyance if we don't ignore failures, tbh.

2023-07-11 06:14 UTC, cmnrd commented
This failed, because this particular report (on reactor-cpp) only works on Linux. Here we need the check on the platform (Ubuntu), and this check was there before the chanhges in this PR.

2023-07-11 07:41 UTC, lhstrh commented on .github/workflows/cpp-tests.yml
> +        if: ${{ github.repository == 'lf-lang/lingua-franca' }}
```suggestion
        if: ${{ github.repository == 'lf-lang/lingua-franca' && matrix.platform == 'ubuntu-latest' }}
```

2023-07-11 12:32 UTC, cmnrd approved these changes

2023-07-11 17:26 UTC, merged