Suppress deprecation warnings so arrays work in Python
lf-lang/lingua-franca pull request #1985
Opened 2023-09-01 12:47 UTC by edwardalee

To work around bug #1981, this PR allows the old syntax for array parameters and states in the Python target, which is the only syntax that currently works.

2023-09-01 17:14 UTC, lhstrh requested changes
This workaround appears to also affect the validation behavior for the `Cpp` target, not just the `Python` target...

2023-09-01 17:14 UTC, lhstrh commented on core/src/main/resources/lib/c/reactor-c
This probably shouldn't be here...

2023-09-01 18:42 UTC, petervdonovan commented
> the old syntax for array parameters and states in the Python target, which is the only syntax that currently works.

No one replied to @oowekyala's comment under the issue:

> I think we should recommend using funny braces to fix this situation.

Why is this not an acceptable near-term solution?

2023-09-01 18:47 UTC, edwardalee commented
Yes, this will work. I will verify and close this.

2023-09-02 17:05 UTC, edwardalee commented
I will update the docs to use syntax `param = {= [1, 2, 3] =}`, so we don't need these changes.

2023-09-02 17:05 UTC, closed without merging