Fix race-condition in _lf_replace_template_token
lf-lang/lingua-franca pull request #2082
Opened 2023-11-03 13:02 UTC by erlingrj

This addresses the problem described in #2081 

The problem was that we moved tokens from the trigger structs to the action structs outside a critical section. This created a race condition with external asynchronus contexts trying to schedule events onto the very same action struct.

This simple solution does the moving of tokens inside i critical section. I think another solution might be to re-think the design. Particularily. 
1. Why does `lf_schedule` put the token on BOTH the event queue AND the action struct? The runtime will later move the token from event queue -> trigger struct and then in the reaction preambles, it moves it from the trigger struct to the action struct.
2. Why is the token moved from trigger-struct to action-struct in the code-generated preamble. It would be more natural to do that from wihin the runtime (which is in a critical section)

2023-11-03 13:03 UTC, erlingrj commented
@edwardalee

2023-11-03 13:24 UTC, erlingrj commented
I had to include `platform.h` for the reaction bodies in order to code-generate a critical section in the reaction preamble. It suggests that maybe another solution is better. Like having the runtime move the token instead of code-generating it.

2023-11-03 21:07 UTC, lhstrh approved these changes
You found a needle in a haystack. Terrific job, @erlingrj.

2023-11-03 22:25 UTC, erlingrj commented
@lhstrh we can wait a little with merging. There might be a better way of addressing this

2023-11-03 22:27 UTC, edwardalee requested changes
Good catch, but I think the critical section needs to be a little bigger or the action struct could become inconsistent.

2023-11-03 22:27 UTC, edwardalee commented on core/src/main/java/org/lflang/generator/c/CReactionGenerator.java
> +            "lf_critical_section_enter(self->base.environment);",
I think the critical section needs to include the two operations above, setting is_present and has_value.  Also the setting of the value below.

2023-11-03 22:27 UTC, edwardalee commented on core/src/main/java/org/lflang/generator/c/CReactionGenerator.java
> +            "lf_critical_section_enter(self->base.environment);",
I think the critical section needs to include the operations above, setting the value.  Also the setting of is_present below.

2023-11-04 08:46 UTC, erlingrj commented
@edwardalee I expanded the critical sections according to your comments.

2023-11-05 16:14 UTC, erlingrj commented
@edwardalee, have you seen this test failure of `ChainWithDelay` before?
```
 Federate 2: FATAL ERROR: Attempted to insert reactions for a trigger that had an intended tag that was in the past. This should not happen under centralized coordination. Intended tag: (2500000, 0). Current tag: (3000000, 0)).
```

2023-11-05 16:23 UTC, erlingrj commented
I was able to reproduce it here and I have the trace of federated communication. Should we discuss it in a separate issue? It might be related to fixes you are working on? The RTI erroneously gives a PTAG to a federate

2023-11-05 16:40 UTC, edwardalee commented
Yes, I'm seeing these kinds of failures. There is an easy solution, but it will mask a more fundamental problem.  The easy solution is to prohibit the use of PTAG except for zero-delay cycles.  We will want to do that eventually, but first we should fix the handling of PTAG because with this easy fix, it will be hard to produce these errors.

2023-11-05 16:50 UTC, erlingrj commented
Separate issue for the ChainWithDelay PTAG problem: https://github.com/lf-lang/lingua-franca/issues/2084

2023-11-06 17:26 UTC, merged