Fix for #2087
lf-lang/lingua-franca pull request #2147
Opened 2024-01-10 14:00 UTC by a-sr

Fixes incorrect scope for detection of duplicate IDs in attribute parameters. Now only duplicate parameter IDs in the same attribute raise and error.
Closes #2087.

2024-01-11 06:29 UTC, lhstrh requested changes
Looks good to me! This should be covered by a unit test, however; one that expects no errors when the same attribute name is used in two different locations and one that expects an error for code that indeed has duplicate attributes.

2024-01-24 23:46 UTC, lhstrh approved these changes

2024-01-25 00:30 UTC, merged

2024-01-25 14:00 UTC, a-sr commented
Thank you for adding the test. I was quite busy the last days.

2024-01-25 17:17 UTC, lhstrh commented
No worries. I realized, however, that we still have some work to do in terms of validation, but that can be done later (see #2162).