Support for Patmos platform
lf-lang/lingua-franca pull request #2383
Opened 2024-08-01 13:27 UTC by EhsanKhodadad

2024-08-02 19:48 UTC, lhstrh commented
@EhsanKhodadad, I enabled CI for you, but it looks like there are still some test failures. Please address those first.

2024-08-03 18:49 UTC, EhsanKhodadad commented
> @EhsanKhodadad, I enabled CI for you, but it looks like there are still some test failures. Please address those first.

Thank you for enabling CI. The tester has not found a header file in the t-crest repository, because t-crest hasn't cloned on the tester's machine.

2024-08-03 19:17 UTC, lhstrh commented
Got it. Can you fix it in the workflow?

2024-08-05 14:28 UTC, EhsanKhodadad commented
> Got it. Can you fix it in the workflow?

Sure

2024-08-22 19:36 UTC, lhstrh commented
Btw, I noticed tests in your fork were failing. Here's a fix for that: https://github.com/lf-lang/lingua-franca/pull/2402

2024-09-09 18:51 UTC, lhstrh commented on .github/workflows/c-patmos-tests.yml
> +      - name: Run Patmos smoke tests
This step isn't actually running any tests.

2024-10-04 12:06 UTC, EhsanKhodadad commented
I have two questions regarding this PR: 
1. Since I haven't implemented multi-thread functions and variables like mutex and thread in lf-patmos-support yet, can I bypass the tests in the concurrent folder temporarily? If so how?
2. In the regular tests, all LF apps, including my HelloPatmos.lf app is tested at the beginning of the test procedure, whereas the Patmos library, including Patmos-clang, still needs to be installed. Can I postpone their execution after the Patmos installation? These tests are written in .github/workflows/c-test.yml file, while the Patmos installation is invoked by c-patmos-test.yml.

2024-10-11 11:40 UTC, EhsanKhodadad commented
> I have two questions regarding this PR:
> 
> 1. Since I haven't implemented multi-thread functions and variables like mutex and thread in lf-patmos-support yet, can I bypass the tests in the concurrent folder temporarily? If so how?
> 2. In the regular tests, all LF apps, including my HelloPatmos.lf app is tested at the beginning of the test procedure, whereas the Patmos library, including Patmos-clang, still needs to be installed. Can I postpone their execution after the Patmos installation? (Something similar to Patmos-tests, where benchmarks are run after Patmos installation.) These tests are written in .github/workflows/c-test.yml file, while the Patmos installation is invoked by c-patmos-test.yml.

@lhstrh @erlingrj @lsk567

2024-10-11 17:45 UTC, erlingrj commented
> I have two questions regarding this PR:
> 
>     1. Since I haven't implemented multi-thread functions and variables like mutex and thread in lf-patmos-support yet, can I bypass the tests in the concurrent folder temporarily? If so how?
> 

Check out your file CPatmosTests.java, here you explicitly run these tests with `buildPatmosConcurrent` remove this function and then change the CI so it doesn't try to run the gradle task associated with ut.

>     2. In the regular tests, all LF apps, including my HelloPatmos.lf app is tested at the beginning of the test procedure, whereas the Patmos library, including Patmos-clang, still needs to be installed. Can I postpone their execution after the Patmos installation? (Something similar to Patmos-tests, where benchmarks are run after Patmos installation.) These tests are written in .github/workflows/c-test.yml file, while the Patmos installation is invoked by c-patmos-test.yml.

You should not run any Patmos-specific tests in C/regular-tests. They should be excluded from there and only be built in there special target. Do a search for `ZEPYHR_UNTHREADED` in the code-base to see the additions needed to disable a test category from the regular tests (and also from the CCpp tests)

2024-10-21 23:40 UTC, lhstrh commented on core/src/main/resources/lib/cpp/reactor-cpp
It doesn't seem like reactor-cpp changes should be included in this PR.

2024-10-21 23:41 UTC, lhstrh reviewed
This overall look good! Let me defer to @erlingrj for final approval.

2024-10-24 15:27 UTC, erlingrj requested changes
Looks good, but we should not update reactor-cpp submodule in this PR

2024-10-24 18:22 UTC, lhstrh commented
@EhsanKhodadad, please make sure reactor-cpp points to [dfdac2c](https://github.com/lf-lang/reactor-cpp/tree/dfdac2c19e8d111cf4741c8bf8f304678a59d025).

2024-10-24 19:13 UTC, erlingrj approved these changes
Looks good, lets merge :)

2024-10-24 20:48 UTC, merged

2024-10-27 06:43 UTC, schoeberl commented
Finally, very good!