Cpp fqn fix
lf-lang/lingua-franca pull request #2431
Opened 2024-10-29 20:07 UTC by OmerMajNition

Cpp runtime has support for fully qualified name but is not available to reaction bodies. This PR adds support for fqn() in reactions.

2024-10-30 04:09 UTC, lhstrh reviewed
Can you please run `./gradlew spotlessApply` to fix the formatting test failure?

2024-10-30 07:57 UTC, cmnrd reviewed
Looks good! While at it, I think it would be nice to add `name()` as well.

The test currently only checks if `fqn()` is available. It would be better to also assert the expected values.

2024-10-30 09:18 UTC, OmerMajNition commented
> Can you please run `./gradlew spotlessApply` to fix the formatting test failure?

2024-10-30 09:19 UTC, OmerMajNition commented
`./gradlew spotlessApply` Done

Added name() support as well and validation in test file

2024-10-30 09:55 UTC, OmerMajNition commented
reactor-cpp/lib/reactor.cc line # 50

`[[maybe_unused]] bool result = inputs_.insert(port).second;`

should become

`[[maybe_unused]] bool result = outputs_.insert(port).second;`

2024-10-30 15:29 UTC, tanneberger requested changes

2024-10-30 15:29 UTC, tanneberger commented on core/src/main/resources/lib/cpp/lfutil.hh
> +  const std::string& fqn() const { return reactor->fqn(); }
please use trailing types: `auto fqn() const -> const std::string&`

2024-10-31 17:56 UTC, tanneberger approved these changes

2024-10-31 18:26 UTC, merged