Set keepalive to true when physical actions exist.
lf-lang/lingua-franca pull request #546
Opened 2021-09-27 17:46 UTC by Soroosh129

Set `keepalive` to `true` if physical actions exist and the user has not explicitly set it to `true` or `false`. See #547.

Also produces a warning whenever both `keepalive` and `threads` are changed because of the presence of a physical action.

2021-09-27 20:35 UTC, edwardalee approved these changes
This looks right to me, especially since the user can override this and set keepalive to false.  In particular, a (peculiar) use of physical actions would schedule them within a reaction rather than externally, in which case one might want keepalive set to false.

2021-09-28 04:10 UTC, lhstrh commented on org.lflang/src/org/lflang/generator/GeneratorBase.xtend
> +                if (target.config?.pairs?.filter[
I don't think this is the right place to do this. I would just add a member `keepAliveSpecified` or something like that to `TargetConfig` that indicates as to whether the property was set explicitly.

2021-09-28 04:16 UTC, lhstrh requested changes
Looks like a sensible policy, but we should not be iterating through the AST to figure out whether a target property was set. If we want to generalize the solution that I suggested in my comment, we could have a `Map<TargetProperty, boolean> isSpecified` in `TargetConfig` that tracks for each property whether it has been set.

2021-09-28 04:17 UTC, lhstrh commented on org.lflang/src/org/lflang/generator/GeneratorBase.xtend
> +                if (target.config?.pairs?.filter[
See below.

2021-09-28 04:35 UTC, Soroosh129 commented
> If we want to generalize the solution that I suggested in my comment, we could have a `Map<TargetProperty, boolean> isSpecified` in `TargetConfig` that tracks for each property whether it has been set.

I like this suggestion a lot. I added a list called `setByUser` to keep track of this.

2021-09-28 04:41 UTC, lhstrh commented
I suppose a list works too, but why not use a map? This is mostly about finding out whether a _particular_ property is set, which requires iterating through the list. I know the time complexity doesn't really matter because it's a short list, but still...

2021-09-28 04:42 UTC, lhstrh commented on org.lflang/src/org/lflang/TargetConfig.xtend
> +    public List<TargetProperty> setByUser = newLinkedList;
Good name!

2021-09-28 04:43 UTC, lhstrh commented
Actually, you want to use a set, not a map.

2021-09-28 04:47 UTC, Soroosh129 commented
> I suppose a list works too, but why not use a map? This is mostly about finding out whether a _particular_ property is set, which requires iterating through the list. I know the time complexity doesn't really matter because it's a short list, but still...

Perhaps a set is more optimized than a list, but adding it will add a whole new dependency to `TargetConfig`.  Most likely for such a small list, the difference in performance is marginal.

2021-09-28 04:54 UTC, lhstrh commented
This is Java, not C. We should use data structures that are optimal for their purpose. Dependencies on standard Java collections implementations are a nonissue.

2021-09-28 17:48 UTC, Soroosh129 commented
It looks like the consensus might be that this is a sensible design. I would still encourage anyone to take a look at the related discussion in #547.

2021-09-28 17:48 UTC, lhstrh approved these changes
Looks good to me! I'll go ahead and merge this.

2021-09-28 17:49 UTC, merged