Benchmark Runner for C Benchmarks
lf-lang/lingua-franca pull request #777
Opened 2021-12-01 06:03 UTC by mattchorlian

Opening this draft PR to track progress of converting all C benchmarks to use the benchmark runner:

- [ ] Port current C++ benchmark runner to C
- [ ] Big.lf
- [ ] Chameneos.lf
- [ ] Counting.lf
- [ ] PingPong.lf
- [ ] ThreadRing.lf
- [ ] Throughput.lf
- [ ] BoundedBuffer.lf
- [ ] CigaretteSmoker.lf
- [ ] Dictionary.lf
- [ ] LogisticMap.lf
- [ ] Philosophers.lf
- [ ] ProdCons.lf
- [ ] SleepingBarber.lf
- [ ] SortedLinkList.lf
- [ ] Apsp.lf
- [ ] FilterBank.lf
- [ ] GuidedSearch.lf
- [ ] MatMul.lf
- [ ] NQueens.lf
- [ ] PiPrecision.lf
- [ ] RadixSort.lf
- [ ] Trapezoidal.lf

2022-01-14 23:44 UTC, mattchorlian commented
I'm noticing that we have BoundedBuffer.lf and ProdCons.lf both here even though they are the same benchmark.  I suppose this is (in part) the Savina naming convention causing confusion again.  In any case, we should decide which one to keep around before merging this in!

2022-01-18 09:30 UTC, cmnrd requested changes
See the comments I made in #852

2022-01-26 07:49 UTC, lhstrh commented
Does this PR also address https://github.com/lf-lang/lingua-franca/issues/765? If not, I think it probably should.

2022-01-26 23:02 UTC, lhstrh requested changes
This looks great, @mattchorlian and @LDeng0205! I've only requested minor changes. Let's merge this into master ASAP.

2022-01-26 23:02 UTC, lhstrh commented on benchmark/C/Savina/src/parallelism/GuidedSearch.lf
This file, along with the included files, should be in a separate directory, as is done with the C++ benchmarks.

2022-01-28 01:55 UTC, housengw commented
Seems like running `MatMul.lf` with more than 1 thread produces a random validation error. I'm guessing it's a memory issue..

2022-01-28 09:30 UTC, cmnrd reviewed
This looks great! Looks like we are close to completing the C benchmarks.

Should we also include the Banking Benchmark #624 here and fix it up?

> Seems like running MatMul.lf with more than 1 thread produces a random validation error. I'm guessing it's a memory issue.

Could you describe what the issue seems to be? Is it a segfault that occurs sometimes? Or is the result invalid (since you mention a validation error)? The MatMul benchmark has a built-in race condition and hence the result is expected to be invalid for parallel execution. This is a bug in the original Savina benchmark...

2022-01-28 09:30 UTC, cmnrd commented on benchmark/runner/conf/benchmark/savina_concurrency_concsll.yaml
>      binary: "SortedLinkList"
```suggestion
    binary: "SortedList"
```

2022-01-28 09:30 UTC, cmnrd commented on .github/workflows/ci.yml
> +    uses: lf-lang/lingua-franca/.github/workflows/benchmark-tests.yml@c-benchmark-runner
This should be reverted to master. There should be no need to change this unless the `benchmark-tests.yaml` workflow itself is updated in this branch.

2022-01-28 23:33 UTC, housengw commented
the `validation error` in multithreaded run of `MatMul.lf` is likely to be a race condition.

2022-02-03 08:22 UTC, lhstrh commented
> the `validation error` in multithreaded run of `MatMul.lf` is likely a race condition.

Could you elaborate?

2022-02-04 04:48 UTC, housengw commented
The MatMul benchmark has random validation errors when running with more than 1 thread. Since there is no segfault and the validation error happens at random indices in the matrix, it is most likely a race condition. 
As @cmnrd mentioned, the MatMul benchmark has a built-in race condition, so running it with multiple threads would cause such an error.

2022-02-04 06:11 UTC, lhstrh approved these changes
Looks ready to me! This is a big feat and will be very useful for the evaluation of the new schedulers in `reactor-c` 🚀🚀🚀 Thanks!

2022-02-04 06:32 UTC, mattchorlian commented
> Should we also include the Banking Benchmark #624 here and fix it up?

We decided to get this merged first and deal with Banking separately @cmnrd

2022-02-04 06:34 UTC, lhstrh commented
> > Should we also include the Banking Benchmark #624 here and fix it up?
> 
> We decided to get this merged first and deal with Banking separately @cmnrd

Comt to thing of it, there is one distinct advantage to adding the other stuff to this PR: we'll have a cleaner history and release notes (if we automatically generate them). Doesn't seem like it would be much work?

2022-02-04 08:25 UTC, cmnrd approved these changes
Looks great! I am happy with both options, merging as is or including banking as well.

2022-02-04 18:24 UTC, LDeng0205 commented
I just added benchmark runner to Banking as well so we could include it with this PR. However, I still have a   java.lang.OutOfMemoryError when I compile it with NumAccounts = 1000.

2022-02-04 19:47 UTC, edwardalee commented
Is this branch merged with master? It looks like it is still generating in-line code, which suggests it is using a version of master that predates scalability-banks.

2022-02-05 00:01 UTC, merged